version: '3.8'

services:
  saveit:
    build: .
    container_name: saveit-app
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
